# Generated by Django 2.1.3 on 2018-11-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(default='UNAMMED', max_length=20),
        ),
    ]
